### ISSUE TITLE
 'BlockDeviceType' object has no attribute 'encrypted'

### ISSUE THREAD

**Issue by dmd** [trailofbits/algo#181]
Ubuntu 14.04.5 LTS
Ansible 2.2.0.0

Trying to install on ec2. I get:

```
An exception occurred during task execution. To see the full traceback, use -vvv.
 The error was: AttributeError: 'BlockDeviceType' object has no attribute 'encryp
ted'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Ekz9U_/ansible_module_ec2_ami_find.py\", line 423, in <module>\n    main()\n  File \"/tmp/ansible_Ekz9U_/ansible_module_ec2_ami_find.py\", line 376, in main\n    'block_device_mapping': get_block_device_mapping(image),\n  File \"/tmp/ansible_Ekz9U_/ansible_module_ec2_ami_find.py\", line 287, in get_block_device_mapping\n    'encrypted': bdm[d
evice_name].encrypted,\nAttributeError: 'BlockDeviceType' object has no attribute
 'encrypted'\n", "module_stdout": "", "msg": "MODULE FAILURE"}

```

**Comment by defunctio** [comment]
See #133

**Comment by dmd** [comment]
It's not clear what the workaround is, and it's definitely a poor error message.

**Comment by gunph1ld** [comment]
it's definitely a poor error first message
https://github.com/trailofbits/algo/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by defunctio** [comment]
@dmd this is using the master branch? Also as @gunphqld said, try to file issues such as this with as much information as possible using the template.

**Comment by dmd** [comment]
Yes, that's on master.

**Comment by dmd** [comment]
As checked out about 20 minutes ago.

**Comment by dmd** [comment]
Using all defaults.

**Comment by dmd** [comment]
https://gist.github.com/dmd/dbc11ad7cc2b70280362e5a2fa6cfc5a

**Comment by dmd** [comment]
### OS / Environment
Ubuntu 14.04.5 LTS

Linux dev 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux


### Ansible version


ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`


dmd@dev:~/algo$ pip show ansible dopy boto azure apache-libcloud six pyopenssl
Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: paramiko, jinja2, PyYAML, setuptools, pycrypto
---
Name: dopy
Version: 0.3.5
Summary: Python client for the Digital Ocean API
Home-page: https://github.com/devo-ps/dopy
Author: Vincent Viallet
Author-email: vincent@devo.ps
License: The MIT License (MIT)
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests
---
Name: boto
Version: 2.20.1
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /usr/lib/python2.7/dist-packages
Requires:
---
Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /usr/local/lib/python2.7/dist-packages
Requires: azure-graphrbac, azure-mgmt, azure-servicebus, azure-storage, azure-batch, azure-servicemanagement-legacy
---
Name: apache-libcloud
Version: 1.4.0
Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Home-page: http://libcloud.apache.org/
Author: Apache Software Foundation
Author-email: dev@libcloud.apache.org
License: Apache License (2.0)
Location: /usr/local/lib/python2.7/dist-packages
Requires:
---
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires:
---
Name: pyOpenSSL
Version: 16.2.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.readthedocs.io/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: cryptography, six

**Comment by defunctio** [comment]
To be reviewed.

**Comment by dmd** [comment]
Note: works on Ubuntu 16.04, fails on 14.04.

**Comment by gunph1ld** [comment]
Can't reproduce. It works well on my clean Ubuntu 14.04 droplet.

@dmd attach the full log with -vvvv

**Comment by dmd** [comment]
Running algo with -vvvv gives

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'BlockDeviceType' object has no attribute 'encrypted'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_c0PP20/ansible_module_ec2_ami_find.py\", line 423, in <module>\n    main()\n  File \"/tmp/ansible_c0PP20/ansible_module_ec2_ami_find.py\", line 376, in main\n    'block_device_mapping': get_block_device_mapping(image),\n  File \"/tmp/ansible_c0PP20/ansible_module_ec2_ami_find.py\", line 287, in get_block_device_mapping\n    'encrypted': bdm[device_name].encrypted,\nAttributeError: 'BlockDeviceType' object has no attribute 'encrypted'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by gunph1ld** [comment]
1. I asked the full log
2. Not algo, but ansible-plabook. [Advanced docs](https://github.com/trailofbits/algo/blob/master/docs/ADVANCED.md)

**Comment by dmd** [comment]
Here you go: 
https://gist.github.com/dmd/0ed5a5165909328324c00a3283dbeb0e

**Comment by defunctio** [comment]
I suspect this is due to the boto version but I haven't looked into it further.

**Comment by dguido** [comment]
I'm closing this as out of date. We changed how AWS deploys work quite a bit since this ticket was filed, and we don't support deploys from 14.04 anyway, only 16.04 and higher.
